name: FITB App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Test and build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm test
      - run: npm run build
